// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwacnopbcpimvfuuvgqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3YWNub3BiY3BpbXZmdXV2Z3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTEyMzcsImV4cCI6MjA2MTIyNzIzN30.FANKbqGr-DMyuQ9JvHCmvyKfUu-CO1WHI5i4Tpqj5Ns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);